project:
  type: website
  output-dir: docs
website:
  open-graph: true
  navbar:
   # background: "#111344"
    background: "#CEDBD5"
    title: "Data meanderings"
    search: true
    collapse: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ajl2718
      - icon: twitter
        href: https://twitter.com/saunteringcat
format:
  html:
    theme: 
      - united
      - custom.scss
    anchor-sections: true
    backgroundcolor: "#E8EDDF"
   # monobackgroundcolor: "#EE3333"
  #  css: styles.css
 #   highlight-style: dracula